services:
  nestapp:
    build: ./
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata:
